#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RouteSpec {
    pub method: &'static str,
    pub opencode_path: &'static str,
    pub axum_path: &'static str,
}

impl RouteSpec {
    pub const fn new(
        method: &'static str,
        opencode_path: &'static str,
        axum_path: &'static str,
    ) -> Self {
        Self {
            method,
            opencode_path,
            axum_path,
        }
    }
}

pub const OPENCODE_ROUTES: &[RouteSpec] = &[
    RouteSpec::new("GET", "/doc", "/doc"),
    RouteSpec::new("GET", "/api/model", "/api/model"),
    RouteSpec::new("GET", "/api/provider", "/api/provider"),
    RouteSpec::new(
        "GET",
        "/api/provider/{providerID}",
        "/api/provider/{provider_id}",
    ),
    RouteSpec::new("GET", "/api/session", "/api/session"),
    RouteSpec::new(
        "GET",
        "/api/session/{sessionID}/context",
        "/api/session/{session_id}/context",
    ),
    RouteSpec::new(
        "GET",
        "/api/session/{sessionID}/message",
        "/api/session/{session_id}/message",
    ),
    RouteSpec::new(
        "POST",
        "/api/session/{sessionID}/compact",
        "/api/session/{session_id}/compact",
    ),
    RouteSpec::new(
        "POST",
        "/api/session/{sessionID}/prompt",
        "/api/session/{session_id}/prompt",
    ),
    RouteSpec::new(
        "POST",
        "/api/session/{sessionID}/wait",
        "/api/session/{session_id}/wait",
    ),
    RouteSpec::new("DELETE", "/auth/{providerID}", "/auth/{provider_id}"),
    RouteSpec::new("PUT", "/auth/{providerID}", "/auth/{provider_id}"),
    RouteSpec::new("GET", "/agent", "/agent"),
    RouteSpec::new("GET", "/command", "/command"),
    RouteSpec::new("GET", "/config", "/config"),
    RouteSpec::new("PATCH", "/config", "/config"),
    RouteSpec::new("GET", "/config/providers", "/config/providers"),
    RouteSpec::new("GET", "/event", "/event"),
    RouteSpec::new("GET", "/experimental/console", "/experimental/console"),
    RouteSpec::new(
        "GET",
        "/experimental/console/orgs",
        "/experimental/console/orgs",
    ),
    RouteSpec::new(
        "POST",
        "/experimental/console/switch",
        "/experimental/console/switch",
    ),
    RouteSpec::new("GET", "/experimental/resource", "/experimental/resource"),
    RouteSpec::new("GET", "/experimental/session", "/experimental/session"),
    RouteSpec::new("GET", "/experimental/tool", "/experimental/tool"),
    RouteSpec::new("GET", "/experimental/tool/ids", "/experimental/tool/ids"),
    RouteSpec::new("DELETE", "/experimental/worktree", "/experimental/worktree"),
    RouteSpec::new("GET", "/experimental/worktree", "/experimental/worktree"),
    RouteSpec::new("POST", "/experimental/worktree", "/experimental/worktree"),
    RouteSpec::new(
        "POST",
        "/experimental/worktree/reset",
        "/experimental/worktree/reset",
    ),
    RouteSpec::new("GET", "/experimental/workspace", "/experimental/workspace"),
    RouteSpec::new("POST", "/experimental/workspace", "/experimental/workspace"),
    RouteSpec::new(
        "GET",
        "/experimental/workspace/adapter",
        "/experimental/workspace/adapter",
    ),
    RouteSpec::new(
        "GET",
        "/experimental/workspace/status",
        "/experimental/workspace/status",
    ),
    RouteSpec::new(
        "POST",
        "/experimental/workspace/sync-list",
        "/experimental/workspace/sync-list",
    ),
    RouteSpec::new(
        "POST",
        "/experimental/workspace/warp",
        "/experimental/workspace/warp",
    ),
    RouteSpec::new(
        "DELETE",
        "/experimental/workspace/{id}",
        "/experimental/workspace/{id}",
    ),
    RouteSpec::new("GET", "/file", "/file"),
    RouteSpec::new("GET", "/file/content", "/file/content"),
    RouteSpec::new("GET", "/file/status", "/file/status"),
    RouteSpec::new("GET", "/find", "/find"),
    RouteSpec::new("GET", "/find/file", "/find/file"),
    RouteSpec::new("GET", "/find/symbol", "/find/symbol"),
    RouteSpec::new("GET", "/formatter", "/formatter"),
    RouteSpec::new("GET", "/global/config", "/global/config"),
    RouteSpec::new("PATCH", "/global/config", "/global/config"),
    RouteSpec::new("POST", "/global/dispose", "/global/dispose"),
    RouteSpec::new("GET", "/global/event", "/global/event"),
    RouteSpec::new("GET", "/global/health", "/global/health"),
    RouteSpec::new("POST", "/global/upgrade", "/global/upgrade"),
    RouteSpec::new("POST", "/instance/dispose", "/instance/dispose"),
    RouteSpec::new("POST", "/log", "/log"),
    RouteSpec::new("GET", "/lsp", "/lsp"),
    RouteSpec::new("GET", "/mcp", "/mcp"),
    RouteSpec::new("POST", "/mcp", "/mcp"),
    RouteSpec::new("DELETE", "/mcp/{name}/auth", "/mcp/{name}/auth"),
    RouteSpec::new("POST", "/mcp/{name}/auth", "/mcp/{name}/auth"),
    RouteSpec::new(
        "POST",
        "/mcp/{name}/auth/authenticate",
        "/mcp/{name}/auth/authenticate",
    ),
    RouteSpec::new(
        "POST",
        "/mcp/{name}/auth/callback",
        "/mcp/{name}/auth/callback",
    ),
    RouteSpec::new("POST", "/mcp/{name}/connect", "/mcp/{name}/connect"),
    RouteSpec::new("POST", "/mcp/{name}/disconnect", "/mcp/{name}/disconnect"),
    RouteSpec::new("GET", "/path", "/path"),
    RouteSpec::new("GET", "/permission", "/permission"),
    RouteSpec::new(
        "POST",
        "/permission/{requestID}/reply",
        "/permission/{request_id}/reply",
    ),
    RouteSpec::new("GET", "/provider", "/provider"),
    RouteSpec::new("GET", "/provider/auth", "/provider/auth"),
    RouteSpec::new(
        "POST",
        "/provider/{providerID}/oauth/authorize",
        "/provider/{provider_id}/oauth/authorize",
    ),
    RouteSpec::new(
        "POST",
        "/provider/{providerID}/oauth/callback",
        "/provider/{provider_id}/oauth/callback",
    ),
    RouteSpec::new("GET", "/project", "/project"),
    RouteSpec::new("GET", "/project/current", "/project/current"),
    RouteSpec::new("POST", "/project/git/init", "/project/git/init"),
    RouteSpec::new("PATCH", "/project/{projectID}", "/project/{project_id}"),
    RouteSpec::new("GET", "/pty", "/pty"),
    RouteSpec::new("POST", "/pty", "/pty"),
    RouteSpec::new("DELETE", "/pty/{ptyID}", "/pty/{pty_id}"),
    RouteSpec::new("GET", "/pty/{ptyID}", "/pty/{pty_id}"),
    RouteSpec::new("PUT", "/pty/{ptyID}", "/pty/{pty_id}"),
    RouteSpec::new("GET", "/pty/{ptyID}/connect", "/pty/{pty_id}/connect"),
    RouteSpec::new(
        "POST",
        "/pty/{ptyID}/connect-token",
        "/pty/{pty_id}/connect-token",
    ),
    RouteSpec::new("GET", "/pty/shells", "/pty/shells"),
    RouteSpec::new("GET", "/question", "/question"),
    RouteSpec::new(
        "POST",
        "/question/{requestID}/reject",
        "/question/{request_id}/reject",
    ),
    RouteSpec::new(
        "POST",
        "/question/{requestID}/reply",
        "/question/{request_id}/reply",
    ),
    RouteSpec::new("DELETE", "/session/{sessionID}", "/session/{session_id}"),
    RouteSpec::new("GET", "/session/{sessionID}", "/session/{session_id}"),
    RouteSpec::new("PATCH", "/session/{sessionID}", "/session/{session_id}"),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/abort",
        "/session/{session_id}/abort",
    ),
    RouteSpec::new(
        "GET",
        "/session/{sessionID}/children",
        "/session/{session_id}/children",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/command",
        "/session/{session_id}/command",
    ),
    RouteSpec::new(
        "GET",
        "/session/{sessionID}/diff",
        "/session/{session_id}/diff",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/fork",
        "/session/{session_id}/fork",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/init",
        "/session/{session_id}/init",
    ),
    RouteSpec::new(
        "DELETE",
        "/session/{sessionID}/message/{messageID}",
        "/session/{session_id}/message/{message_id}",
    ),
    RouteSpec::new(
        "GET",
        "/session/{sessionID}/message/{messageID}",
        "/session/{session_id}/message/{message_id}",
    ),
    RouteSpec::new(
        "DELETE",
        "/session/{sessionID}/message/{messageID}/part/{partID}",
        "/session/{session_id}/message/{message_id}/part/{part_id}",
    ),
    RouteSpec::new(
        "PATCH",
        "/session/{sessionID}/message/{messageID}/part/{partID}",
        "/session/{session_id}/message/{message_id}/part/{part_id}",
    ),
    RouteSpec::new(
        "GET",
        "/session/{sessionID}/message",
        "/session/{session_id}/message",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/message",
        "/session/{session_id}/message",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/permissions/{permissionID}",
        "/session/{session_id}/permissions/{permission_id}",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/prompt_async",
        "/session/{session_id}/prompt_async",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/revert",
        "/session/{session_id}/revert",
    ),
    RouteSpec::new(
        "DELETE",
        "/session/{sessionID}/share",
        "/session/{session_id}/share",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/share",
        "/session/{session_id}/share",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/shell",
        "/session/{session_id}/shell",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/summarize",
        "/session/{session_id}/summarize",
    ),
    RouteSpec::new(
        "GET",
        "/session/{sessionID}/todo",
        "/session/{session_id}/todo",
    ),
    RouteSpec::new(
        "POST",
        "/session/{sessionID}/unrevert",
        "/session/{session_id}/unrevert",
    ),
    RouteSpec::new("GET", "/session", "/session"),
    RouteSpec::new("POST", "/session", "/session"),
    RouteSpec::new("GET", "/session/status", "/session/status"),
    RouteSpec::new("GET", "/skill", "/skill"),
    RouteSpec::new("POST", "/sync/history", "/sync/history"),
    RouteSpec::new("POST", "/sync/replay", "/sync/replay"),
    RouteSpec::new("POST", "/sync/start", "/sync/start"),
    RouteSpec::new("POST", "/sync/steal", "/sync/steal"),
    RouteSpec::new("POST", "/tui/append-prompt", "/tui/append-prompt"),
    RouteSpec::new("POST", "/tui/clear-prompt", "/tui/clear-prompt"),
    RouteSpec::new("GET", "/tui/control/next", "/tui/control/next"),
    RouteSpec::new("POST", "/tui/control/response", "/tui/control/response"),
    RouteSpec::new("POST", "/tui/execute-command", "/tui/execute-command"),
    RouteSpec::new("POST", "/tui/open-help", "/tui/open-help"),
    RouteSpec::new("POST", "/tui/open-models", "/tui/open-models"),
    RouteSpec::new("POST", "/tui/open-sessions", "/tui/open-sessions"),
    RouteSpec::new("POST", "/tui/open-themes", "/tui/open-themes"),
    RouteSpec::new("POST", "/tui/publish", "/tui/publish"),
    RouteSpec::new("POST", "/tui/select-session", "/tui/select-session"),
    RouteSpec::new("POST", "/tui/show-toast", "/tui/show-toast"),
    RouteSpec::new("POST", "/tui/submit-prompt", "/tui/submit-prompt"),
    RouteSpec::new("GET", "/vcs", "/vcs"),
    RouteSpec::new("POST", "/vcs/apply", "/vcs/apply"),
    RouteSpec::new("GET", "/vcs/diff", "/vcs/diff"),
    RouteSpec::new("GET", "/vcs/diff/raw", "/vcs/diff/raw"),
    RouteSpec::new("GET", "/vcs/status", "/vcs/status"),
];
